### ISSUE TITLE
After signing in when calling the authorized Webp.Ap Controllers (Opportunities, Regions etc.) the JWT signature validation fails

### ISSUE THREAD

**Issue by tmol** [OfficeDev/ProposalManager#1]
Hi,

see below. If I remove manually the msal.js and app related items from the local storage, the standard account selection popup appears, but the same error is thrown after selecting the account.
Any ideas would be appreciated.

Thank you,

Tibi

Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler:Information: Failed to validate the token.

Microsoft.IdentityModel.Tokens.SecurityTokenInvalidSignatureException: IDX10503: Signature validation failed. Keys tried: 'Microsoft.IdentityModel.Tokens.X509SecurityKey , KeyId: 7_Zuf1tvkwLxYaHS3q6lUjUYIGw
'.
Exceptions caught:
 ''.
token: '{"alg":"RS256","typ":"JWT","nonce":"AQABAAAAAADXzZ3ifr-GRbDT45zNSEFEM0DmZQQDP4LcGGI1PCOuvYj5SYjAIzTBespKo-5opHm2Fj6TV1A8Yc8Gs1Z4X3QSVPfwm066lWZLsXItQhvFQSAA","x5t":"7_Zuf1tvkwLxYaHS3q6lUjUYIGw","kid":"7_Zuf1tvkwLxYaHS3q6lUjUYIGw"}.{"aud":"https://graph.microsoft.com","iss":"https://sts.windows.net/********-84bf-42e7-b018-********/","iat":1536556988,"nbf":1536556988,"exp":1536560888,"acct":0,"acr":"1","aio":"42BgYMgskmBja1avvPckxy5//9ZfL4wCNlRd8k8Vd55u//TmrbsA","amr":["pwd"],"app_displayname":"*** Banking Proposal Manager","appid":"*****-1ae1-4f44-9ddb-******","appidacr":"0","e_exp":262800,"family_name":"Molnar","given_name":"******","ipaddr":"194.117.242.15","name":"******","oid":"ce8b3178-2aea-47da-91e6-0c6d2f631a42","platf":"3","puid":"10030000ABAAA71E","scp":"Directory.ReadWrite.All email Files.ReadWrite.All Group.ReadWrite.All Mail.Read Mail.Send openid profile Sites.ReadWrite.All User.Read User.Read.All User.ReadBasic.All","sub":"p8GdCvFZwl7baAR883KHq06RT5sOBwkr45IjBozx5Io","tid":"76303dcf-84bf-42e7-b018-0dd851ffa716","unique_name":"******@******.onmicrosoft.com","upn":"*****@******.onmicrosoft.com","uti":"8ell6kQiDky0UkykGTEEAA","ver":"1.0","xms_st":{"sub":"3xjIRDSqTEonFQR6qbMzjg6KFvnQwfvncC60_apf7hU"}}'.
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()

**Comment by abhishek-pc** [comment]
The issue seems to be that the app registration (client ID) and secret are not configured properly, please make sure to follow the app regsitration steps and the app secret is generated and that the web api is added and the right values copied to both appsettings.json and appsettings.js, as detailed in Section 3 of the [Getting Started Guide](https://github.com/OfficeDev/ProposalManager/blob/master/Proposal_Manager_Getting_Started_Guide.docx)

**Comment by tmol** [comment]
To be sure I created a new password for the app in https://apps.dev.microsoft.com.
Both settings are using the same application id and password.
I paste here the configuration settings, maybe you see something suspicion.
What is interesting that if I validate the JWT token used the requests from the web components, in https://jwt.ms/, it validates the signature, but it says that is an Azure AD v1 token (the same token signature cannot be validated by the Asp.Net Core Web API ADBearer extension, this is the reason of this issue)

--------------------------BEGIN AppSettings.js-----------------------------------
// General settings
export const appUri = 'https://localhost:44375';

// Authentication settings
export const clientId = 'APPLICATION_ID';
export const redirectUri = appUri + "/";
export const instanceId = 'https://login.microsoftonline.com/';
export const graphScopes = ["offline_access", "profile", "User.ReadBasic.All", "mail.send"];
export const graphScopesAdmin = ["offline_access", "profile", "User.Read.All", "mail.send", "Sites.ReadWrite.All", "Files.ReadWrite.All", "Group.ReadWrite.All"];
export const webApiScopes = ['openid', 'email', 'profile', 'offline_access', 'User.Read.All', 'Mail.Send', 'Sites.ReadWrite.All', 'Files.ReadWrite.All', 'Group.ReadWrite.All', 'Directory.ReadWrite.All'];
export const clientSecret = 'APPLICTAION_PASSWORD';
//export const authority = 'https://login.microsoftonline.com/onterawe.onmicrosoft.com'; 
export const authority = null; // Null for login as common (multi-tenant also) eg. https://login.microsoftonline.com/common/oauth2/v2.0/authorize
export const teamsAppInstanceId = "<to be updated>";

--------------------------END AppSettings.js-----------------------------------

and here is the AzureAd section of the appsettings.json

  "AzureAd": {
    "AppId": "APPLICATION_ID",
    "ClientId": "APPLICATION_ID",
    "ClientSecret": "APPLICTAION_PASSWORD", // This sample uses a password (secret) to authenticate. Production apps should use a certificate.
    "Instance": "https://login.microsoftonline.com/",
    "Domain": "********.onmicrosoft.com",
    "TenantId": "AAD_DIRECTORY_ID",
    //"TenantId": "common",
    "CallbackPath": "/signin-oidc",
    //"BaseUrl": "https://******************.azurewebsites.net/",
    "BaseUrl": "https://localhost:44375/",
    "Scopes": "openid email profile offline_access User.Read.All Mail.Send Sites.ReadWrite.All Files.ReadWrite.All Group.ReadWrite.All Directory.ReadWrite.All",
    "GraphResourceId": "https://graph.microsoft.com/",
    "GraphScopes": "User.Read.All Mail.Send Sites.ReadWrite.All Files.ReadWrite.All Group.ReadWrite.All Directory.ReadWrite.All"
  },

**Comment by abhishek-pc** [comment]
Can you please clear the cache and cookies from the browser, close the browser and retry. If this does not work, it would be great if you can send us the token, so that we can take a look at the same.

**Comment by tmol** [comment]
I did that both on Edge and Chrome, I have the same result. The token is below, it validates on jwt.ms. Thank you for your help.

eyJ0eXAiOiJKV1QiLCJub25jZSI6IkFRQUJBQUFBQUFEWHpaM2lmci1HUmJEVDQ1ek5TRUZFbzhIZ21RbUYyWXQwU1pYRmdjeFc3MDlJR28xMEpTZHhEVGRDdlloeVA1ZlhzdXRTb2NZcFZyTVlKZlgyd3BZWWZVMWFCZ2tVamw4Q05UM0xGcDRxaHlBQSIsImFsZyI6IlJTMjU2IiwieDV0IjoiN19adWYxdHZrd0x4WWFIUzNxNmxValVZSUd3Iiwia2lkIjoiN19adWYxdHZrd0x4WWFIUzNxNmxValVZSUd3In0.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC83NjMwM2RjZi04NGJmLTQyZTctYjAxOC0wZGQ4NTFmZmE3MTYvIiwiaWF0IjoxNTM2Njg5NzI4LCJuYmYiOjE1MzY2ODk3MjgsImV4cCI6MTUzNjY5MzYyOCwiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IjQyQmdZRER3VGkwSy8vd3ZMQ1J2MGIwWFI4dDN4dnE4OUoxL2ozRXpNOE1HYlpkcmNzOEIiLCJhbXIiOlsicHdkIl0sImFwcF9kaXNwbGF5bmFtZSI6ImlRdWVzdCBCYW5raW5nIFByb3Bvc2FsIE1hbmFnZXIiLCJhcHBpZCI6ImQ0N2U5YmM4LTFhZTEtNGY0NC05ZGRiLTQyYjA1ODEyMGM5YyIsImFwcGlkYWNyIjoiMCIsImVfZXhwIjoyNjI4MDAsImZhbWlseV9uYW1lIjoiTW9sbmFyIiwiZ2l2ZW5fbmFtZSI6IlRpYm9yIiwiaXBhZGRyIjoiMTg4LjI0LjI4LjE4MyIsIm5hbWUiOiJUaWJvciBNb2xuYXIiLCJvaWQiOiJjZThiMzE3OC0yYWVhLTQ3ZGEtOTFlNi0wYzZkMmY2MzFhNDIiLCJwbGF0ZiI6IjMiLCJwdWlkIjoiMTAwMzAwMDBBQkFBQTcxRSIsInNjcCI6IkRpcmVjdG9yeS5SZWFkV3JpdGUuQWxsIGVtYWlsIEZpbGVzLlJlYWRXcml0ZS5BbGwgR3JvdXAuUmVhZFdyaXRlLkFsbCBNYWlsLlJlYWQgTWFpbC5TZW5kIG9wZW5pZCBwcm9maWxlIFNpdGVzLlJlYWRXcml0ZS5BbGwgVXNlci5SZWFkIFVzZXIuUmVhZC5BbGwgVXNlci5SZWFkQmFzaWMuQWxsIiwic3ViIjoicDhHZEN2Rlp3bDdiYUFSODgzS0hxMDZSVDVzT0J3a3I0NUlqQm96eDVJbyIsInRpZCI6Ijc2MzAzZGNmLTg0YmYtNDJlNy1iMDE4LTBkZDg1MWZmYTcxNiIsInVuaXF1ZV9uYW1lIjoidGlib3IubW9sbmFyQHRpYm9ybW9sbmFyaXF1ZXN0Lm9ubWljcm9zb2Z0LmNvbSIsInVwbiI6InRpYm9yLm1vbG5hckB0aWJvcm1vbG5hcmlxdWVzdC5vbm1pY3Jvc29mdC5jb20iLCJ1dGkiOiIyaFdDamtpQXMwR2htVXVuaUU1REFBIiwidmVyIjoiMS4wIiwieG1zX3N0Ijp7InN1YiI6IjN4aklSRFNxVEVvbkZRUjZxYk16amc2S0Z2blF3ZnZuY0M2MF9hcGY3aFUifX0.IIRZxqooddJvWw1o18Eo1nQW3OLvw6KZ5xLGj1TcS7UQAgSIOqRLyAUUJriv_QcvKfw2QvyL3RhTfvX7hjQ1ct-CjGYTpDO3ai6NIpGwMY1PNIliM7FRHFdb-e6_0ZcFNlqj-A-j0FT2NQ87lA9ZQUt40Pl577GrMy-3AlSTk7HO8A0xFxvteLil_0z0IEYIUrx4tvq6g3ezaUOtPR6jlGk2ZNqtuP2wvEWOxBsQMCWjDxtdqVvMUaewctjaxiY9X1jZ654W_J2_TaWCyS_LRuuGjZcXHGam1uRZ42ik3x7qcUmJTEXv3wXaqZGMTwKsaJnTgnoUriwVT9wymoFK6Q

**Comment by v-jadalz** [comment]
There should be 2 or 3 tokens in the local store: GraphToken, WebApiToken & AdminGraphToken (this last one only will be requested if user is administrator and clicks on administration option in the web UI).

Can you send us the WebApiToken? The audience should look something like: 

"aud": "bfebfe3bfe-3bfe-4800-871e-12345678",
  "iss": "https://login.microsoftonline.com/5tg16324-e554-4d84-83de-59a03f343e20/v2.0"

Thanks

**Comment by tmol** [comment]
Hi  this could be a problem. I have 2 tokens, GraphToken and WebApiToken, but both of them have "aud": "https://graph.microsoft.com". If I delete all data from the LocalStorage, refresh, sign in, choose the account, then in AuthHelper.js the handleWebApiToken function is called in the following sequence:
 - from AuthHelper.js loginPopup - seems to be a valid web apoi token
- from AppBrowser in login in the catch after the this.authHelper.acquireTokenSilent() then this.authHelper.acquireWebApiTokenSilent() which in turn calls this.authClient.acquireTokenSilent(webApiScopes, authority) and then we have handleWebApiToken(accessToken); - this token is a graph token! which overrides the web api token from the previous call!! This should be a config issue.

So this was a very helpful observation that the webApiToken I sent to you in fact is a graph token, thank you. I dig in, maybe you have some ideas why the second call retrieves a graph token. Also I do not see why AppBrowser after calling the authHelper.loginPopup which registers the web api token we call this.authHelper.acquireTokenSilent() and then  this.authHelper.acquireWebApiTokenSilent() (which does not work well).

**Comment by abhishek-pc** [comment]
Hope you have been able to make progress with the deployment. Please let us know if you are continuing to face any issues.

**Comment by rosenfeldeugen** [comment]
Hi,

The authHelper.loginPopup() functions returns a webApi token that is stored in localStorage. The function is executed at line 140 in AppBrowser. At line 144 in AppBrowser the authHelper.acquireWebApiTokenSilent() is executed which receives a graphToken that gets stored in localStorage replacing the webApi token.
After commenting the line 144 everything works as expected.
I don't know if this is the right way.

**Comment by v-jadalz** [comment]
That is fine, we have noted the issue so it can be addressed in the next update. Thanks.

**Comment by rosenfeldeugen** [comment]
When the application is loaded in Teams there is an issue with the authentication mechanism.
The redirectUrl should point to appUri + '/tab/tabauth' instead of appUri. Unfortunately if you set this in AppSetings the Proposal Manager is not usable as a standalone application.

In order to make the application working, I had to change the line number 26 inside AuthHelper library to:
redirectUri: redirectUri + (utils.inTeams() ? 'tab/tabauth' : '')

Is this the right approach?

**Comment by rosenfeldeugen** [comment]
Inside AppBrowser at line 161 I had to replace:
this.authHelper.acquireWebApiTokenSilent()
with
this.authHelper.acquireTokenSilent()

in order not to replace the WebApi token and to obtain a GraphToken

**Comment by abhishek-pc** [comment]
That is fine, we have noted the issue so it can be addressed in the next update. Thanks.
