### ISSUE TITLE
the O365 Modern Auth window doesn't go away while call Proposal manager

### ISSUE THREAD

**Issue by wjxhwcs** [OfficeDev/ProposalManager#9]
when you click the proposal manager tab in Teams, Modern auth window popup, we input credential, but it doesn't go away, keeps poping up. going no where.

who should troubleshoot this issue? Github proposal manager developer or Microsoft CSS?

**Comment by joshyjjp** [comment]
The issue indicated is fixed in latest version (v2) - please use this version. Let us know if any other issues - we will help

**Comment by Elypsia** [comment]
Apparently this is still not solved./
